# Generated by Django 4.0.2 on 2022-02-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='calorie_consumption',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Расход калорий (в день)'),
        ),
    ]
