# Generated by Django 4.0.2 on 2022-02-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_day_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
