# Generated by Django 4.0.2 on 2022-02-05 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0004_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('calories', models.PositiveIntegerField(verbose_name='Калорийность на 100г')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField(default=100, verbose_name='Количество грамм')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_food', to='diary.food')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_food', to='diary.meal')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='meals',
            field=models.ManyToManyField(related_name='meals', through='diary.MealFood', to='diary.Meal'),
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(related_name='food', through='diary.MealFood', to='diary.Food'),
        ),
    ]
