# Generated by Django 4.0.2 on 2022-02-13 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_alter_meal_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
    ]
