# Generated by Django 4.0.2 on 2022-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_remove_meal_calories'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Калорий всего'),
        ),
    ]
