# Generated by Django 4.0.2 on 2022-02-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_alter_day_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now=True, verbose_name='Время приема пищи')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='diary.day')),
            ],
        ),
    ]
