# Generated by Django 4.0.2 on 2022-02-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_meal_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.TimeField(verbose_name='Время приема пищи'),
        ),
    ]
