# Generated by Django 4.0.2 on 2022-02-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_alter_food_meals_alter_meal_food_alter_meal_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ('day', 'time')},
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=50, verbose_name='Калорий всего'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='meals',
            field=models.ManyToManyField(related_name='meals', through='diary.MealFood', to='diary.Meal'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ManyToManyField(through='diary.MealFood', to='diary.Food', verbose_name='Еда'),
        ),
    ]
