# Generated by Django 4.0.2 on 2022-02-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_alter_meal_options_meal_calories_alter_food_meals_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0, verbose_name='Калорий всего'),
        ),
    ]
